server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservice2
    username: root
    password: 7348207455
    driver-class-name: com.mysql.cj.jdbc.Driver
  # application:
  #   name: user_service
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  config:
    import: optional:configserver:http://localhost:8086
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-91704194.okta.com/oauth2/default
      client:
        registration:
          my-internal-client:
            provider: okta
            authorization-grant-type: client_credentials
            scope: internal
            client-id: 0oag3sbjfnbjCWt3b5d7
            client-secret: amP2d63HtNwHnnoylb__w-AwIOl1J7eMvu-bdFIt7ZKilpq8COB4O1cAZhEIqech

        provider:
          okta:
            issuer-uri: https://dev-77584981.okta.com/oauth2/default

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

okta:
  oauth2:
    issuer: https://dev-91704194.okta.com/oauth2/default
    audience: api://default
