server:
  port: 8086

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ranjeetyadav7348/microservice_config_server
          clone-on-start: true
